### ISSUE TITLE
Referencing installed plugins

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#12]
To know what plugins exist, users must navigate top menu and are shown a pop menu. Window font and table layout do not align with other typography or design choices within napari. Table lacks some functionality (can i uninstall the plugin? update it?) and may be hard to read with scale (as user adds many plugins).
__________________________________________________________
**Recommendation**

Planned updates to plugin experience in the works but consider update to format closer to current window layout (add as a window panel like layer list and layer consol).

Minor issue
●●○   Medium design work
▼▼▽   Medium development work

**Comment by sofroniewn** [comment]
This has been improved since the merge of https://github.com/napari/napari/pull/1357 and there is now a new plugin management dialog.

**Comment by goanpeca** [comment]
What is the estatus of this, or the remaining work to align with the initial suggestions @napari/core-devs ?

Thanks :)

**Comment by tlambert03** [comment]
I don't think there was anything in here that wasn't fixed in the updated plugin installer.  @liaprins-czi?

**Comment by sofroniewn** [comment]
That is my understanding too, I think this was mostly addressed by the updates to the plugin installer, and it would be a new round of work to evaluate the current plugin installer and proposed improvements to it.

**Comment by goanpeca** [comment]
In that case, do we close this issue?

**Comment by sofroniewn** [comment]
Maybe let's wait to hear from @liaprins-czi if she any additional recommendations. If not we can close.

Here is a screenshot of the latest - none of which was in place when the heuristics analysis was done:

<img width="1192" alt="Screen Shot 2021-03-22 at 6 51 48 PM" src="https://user-images.githubusercontent.com/6531703/112080808-db194900-8b3f-11eb-90c8-d9011aebab93.png">

**Comment by liaprins-czi** [comment]
Yes, let's close it now; if we need to make usability updates related to the napari Hub work, we can figure that out when it comes along, but it would be separate from this.
