### ISSUE TITLE
UI copy

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#14]
Colormap + points' shape dropdown names should not have underscores, should be full words.
__________________________________________________________
**Recommendation**

Use full words when labeling options.

Best practice
○○○   No design work
▼▽▽   Low development work

![uicopy](https://user-images.githubusercontent.com/53277128/95919712-f39c6080-0d62-11eb-8234-d5c432b426f6.png)
![uicopy2](https://user-images.githubusercontent.com/53277128/95919713-f434f700-0d62-11eb-9f19-579de03d98c2.png)

**Comment by goanpeca** [comment]
This is something that I touched when doing https://github.com/napari/napari/pull/2429

So I can continue with this.

(Can someone assign me :) ?)

**Comment by goanpeca** [comment]
@sofroniewn where do the colormap names come from?

**Comment by sofroniewn** [comment]
Many are defined in this list https://github.com/napari/napari/blob/9f7ac0d7a579ee1953ebe36f89223407df39f78f/napari/utils/colormaps/matplotlib_cmaps.txt and are named after vispy or matplotlib colormaps.

We then have this function which tries to get a colormap based on its "name" https://github.com/napari/napari/blob/b70712aa9cb944971044c2b8d0e1178121b35e5f/napari/utils/colormaps/colormap_utils.py#L308-L340

If we changed these names we'd have to think about where to do that, does it change the actual `Colormap.name` in napari or do we just have a look up table which gets us back and forth from original name to display name?

For points symbols they get defined/ mapped here https://github.com/napari/napari/blob/master/napari/layers/points/_points_constants.py#L39-L99, but they are then used by vispy which does expect those names - so we'd have to also allow for some conversion somewhere too ...

I'm not sure what's best. Open to suggestions!

**Comment by goanpeca** [comment]
>do we just have a look up table which gets us back and forth from original name to display name?

I would say this one.

**Comment by goanpeca** [comment]
I have already added the mapping on the bottom for points 
https://github.com/napari/napari/blob/master/napari/layers/points/_points_constants.py#L82

So we are good there, and why I suggest we keep doing mappings (so that they can be translated easily.)

**Comment by sofroniewn** [comment]
> So we are good there, and why I suggest we keep doing mappings (so that they can be translated easily.)

Sounds good to me!
