### ISSUE TITLE
Square brush

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#25]
Square brush shape doesn't seem to provide any value over circle shape. User has unnecessary burden of extra choice.
__________________________________________________________
**Recommendation**

I suspect the square brush shape is a relic since it was the original shape before I had suggested to change it to circle. However, we don't need both, so we can just get rid of the square shape and then the user has less options confronting them.

Best practice
○○○   No design work
▼▽▽   Low development work

![squarebrush](https://user-images.githubusercontent.com/53277128/95921668-88ed2400-0d66-11eb-9027-664f76f321fb.png)

**Comment by ppwadhwa** [comment]
@liaprins-czi Do we still need a drop down menu item for this if there is only 1 option?

**Comment by liaprins-czi** [comment]
@ppwadhwa No, we should just remove the entire "brush shape:" section from the UI, and brush can be a circle by default instead

**Comment by ppwadhwa** [comment]
Update: The square brush shape has been removed from the UI.  Eventually, we're going to completely remove it from the code base.
