### ISSUE TITLE
Indicate file extension

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#31]
When I go to save (anything: layer(s), screenshot), the save modal doesn't indicate what file type it will be saved as. When I tried to include a filetype extension as part of the name I provided in the text field, the image did not save. However, there was no indication / messaging / warning.
__________________________________________________________
**Recommendation**

By default, include the file extension + (a default name?) in the save modal's text field. If something goes wrong with user's save, provide messaging so they can recover or learn what happened.

Moderate issue
●○○   Low design work
▼▼▽   Medium development work

Relates to #5 

Current view when try to save file in app:
<img width="1101" alt="savefiletypes" src="https://user-images.githubusercontent.com/53277128/95920018-7f15f180-0d63-11eb-9b75-3f4f0795aa6d.png">

**Comment by goanpeca** [comment]
This sounds like a good issue to work on @ppwadhwa 

For the case of the layers 
https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L428

Some reference docs: https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileName

**Comment by goanpeca** [comment]
Fixed by https://github.com/napari/napari/pull/2650
