### ISSUE TITLE
Maintain most recent directory

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#32]
When I navigate to a location on my machine via an import modal or a save modal provided by napari, it defaults to a root area of my folders every time. It doesn't remember the last place I had selected.
__________________________________________________________
**Recommendation**

Remember user's last-selected location (independent for opening a file and saving a file), and automatically open to that directory in the import/save modals respectively.

Best practice
●○○   Low design work
▼▼▽   Medium development work

**Comment by Czaki** [comment]
I suggest to remember few last directories (maybe ten?)

**Comment by goanpeca** [comment]
>I suggest to remember few last directories (maybe ten?)

@czaki , who would this work, are you suggesting an extra menu entry on `File` menu to have `Open recent folder...` or something?
 
<img width="301" alt="Screen Shot 2021-03-21 at 10 56 48 PM" src="https://user-images.githubusercontent.com/3627835/111938787-ba49e880-8a98-11eb-9b20-af34c13e3336.png">

---

@ppwadhwa this sounds like good issue to work on. We can add `open_recent_directories` and `save_recent_directories` list to the `ApplicationSettings`. Even if we just use one entry for now.

https://github.com/napari/napari/blob/master/napari/utils/settings/_defaults.py#L52

And 

https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L495

Where we can store the `last_visited_dir` in the settings.

**Comment by Czaki** [comment]
I suggest using [`setHistory`](https://doc.qt.io/qt-5/qfiledialog.html#setHistory) when creating dialog widget and added to history last 10 opened directories. So when the user wants to open/save some files then could faster navigate using the lasts locations. 

I personally use 2-3 locations parallel.

**Comment by liaprins-czi** [comment]
As a minimum, when the file-selection dialog opens, it should open to the file folder that was last used. 

However, beyond that, we can list the other most-recently used folders. On a Mac, I know where these would show up, but I am not sure where / if they go for other operating systems:

<img width="770" alt="Screen Shot 2021-03-23 at 3 10 26 PM" src="https://user-images.githubusercontent.com/53277128/112226160-0c9b1e80-8beb-11eb-801b-806abf190437.png">

When click on the folder button in screenshot above, it opens a dropdown (shown below), with a "Recents" section:

<img width="383" alt="Screen Shot 2021-03-23 at 3 10 38 PM" src="https://user-images.githubusercontent.com/53277128/112226173-10c73c00-8beb-11eb-8b4a-33ed51423361.png">

**Comment by Czaki** [comment]
Non all native open file dialog support history (gnome has a problem with this for example), but if I good remember Windows and macOS should work well. 

Maybe in GNOME it was fixed since my last try (I personally use Qt one instead of native File Dialog).

**Comment by goanpeca** [comment]
@sofroniewn I think we can close this one, 

Fixed by napari/napari#2467
