### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#33]
Lucy: As non-python expert, I tried installing on my own but was confused by error feedback (I believe it was around skimage?), so asked my housemate (a VP of engineering w/years of python experience). He ALSO got stuck and had to troubleshoot workarounds (error: Please install the `scikit-image` package (instead of `skimage`)). As a nonprogrammer, I didn't turn to github out of bashfulness (and eventual assistance from a programmer).

Lia: I was unable to install napari following the instructions in the docs and had to create a [GH issue](https://github.com/napari/napari/issues/1474) (luckily the response in the GH issue did help me eventually install but it still took a lot of back and forth).
__________________________________________________________
**Recommendation**

I need to recreate this to see if it's a docs error (I think we hit a problem with skimage vs scikit-image) but consider installation for beginners with no upfront knowledge.

Ideally fix the issue with napari that prevented it from installing.

Otherwise, include guidance in docs to help users overcome this particular issue, now that we are aware of it.

Critical issue
○○○   No design work
▼▼▼   High development work

**Comment by Czaki** [comment]
napari should have no scikit-image dependency. Where You need scikit-image?

**Comment by liaprins-czi** [comment]
@LCObus was experiencing the issue relating to scikit image... not sure if you remember the details around it, Lucy?

**Comment by LCObus** [comment]
If my memory serves me, it was a naming convention error- the [napari documentation](https://napari.org/) tells the user to type "skimage" rather than "scikit-image" . Unfortunately, since my housemate was the one rapidly troubleshooting and changing code, I have trouble remembering his adjustments beyond that.
<img width="751" alt="Screen Shot 2020-10-14 at 5 03 26 PM" src="https://user-images.githubusercontent.com/63607867/96058048-32074d80-0e3f-11eb-811e-dd1c6e85c443.png">

**Comment by liaprins-czi** [comment]
@LCObus It sounds like maybe your particular install-related issue is more to do with the website content/documentation? Or do you think it should have been addressed during the installation process itself (i.e. the errors served, or being able to more gracefully handle your input)? If you think it is more that that docs are giving incorrect guidance, we can create a separate issue for that, and tag it as website content-related!

**Comment by justinelarsen** [comment]
We should make a napari[docs] to install all of the requirements needed to run our examples.

**Comment by liu-ziyang** [comment]
This issue is scheduled for our Oct 20th - Nov 2nd Sprint

**Comment by liu-ziyang** [comment]
compiling list of somewhat related issues:
https://github.com/napari/napari/issues/1742
https://github.com/napari/napari/issues/1627
https://github.com/napari/napari/issues/1477
https://github.com/napari/napari/issues/1340
https://github.com/napari/napari/issues/1112
https://github.com/napari/napari/issues/1070

I think one theme that I can see is that the installation requires some knowledge in different scenarios. Be it compiling knowledge when python running into c compilation hell on a particular machine, or past python app experience when bundled windows app opens an empty terminal, etc.

The first step I can think of to these problems is to extend our installation guide to correct misunderstandings and include troubleshoots from lessons that we learned. We may also want to include the possible skill required to perform each troubleshooting action in edge cases.
Secondly, as we continue to monitor the new issues, I believe a comprehensive user study would help capture possible misunderstood of the installation guide and give us more signals of the existing experience of our user group.
Thirdly, I think it is about time to start advertising bundled apps to people that are away from the python world. They may not intend to interact with the app through coding and/or IDE, we should clearly point out the bundled app option for them before they go through any installation guide through pip or source code, and felt this is not for them to try if they don't have programming knowledge.

**Comment by LCObus** [comment]
I agree with these recommendation Ziyang- update the install guide to solve the problem before it happens/offer frequently known troubleshooting (we've seen this happen socially amongst the team when newcomers like lia and i have failed) and direct users towards one install option over another based on their background knowledge/expertise.

Re: user study, installation and its guide should be assessed. There is a lot to cover in the H12021 usability study, and I want to ensure the docs/website is updated as well, so we might have a staggered or revisited approach. I will definitely follow up with you closer to learn some of your expectations and assumptions in this area.

**Comment by liu-ziyang** [comment]
The documentation update is merged, which should covered the existing issues that we are aware of so far. we can close the issue for now, we will continue the related effort in h1 2021 usability research to improve our guides
