### ISSUE TITLE
Dysfunctional menubar options

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#34]
Often the menubar is not clickable/no options open if I don't have an image on the canvas yet. But I want to use the "File > Import image" option to get an image in the canvas in the first place, and cannot until I instead drag in an image.
Also, "File > Open Files as Stack" does not seem to do anything?

In the napari top bar menu, when go to "View > Toggle menubar visibility (command + M)" nothing changes. This is regardless of whether the layer controls + list are inside the napari viewer, popped out as their own windows, or closed.
__________________________________________________________
**Recommendation**

Fix so the menubar options open / work consistently.

Could be good to have part of tutorial section somewhere explain all the different options within the menubar, because it's hard to tell how to use them sometimes or what to expect.

Selecting to "Toggle menubar visibility" should do what it claims: I had assumed the menubar functionality referred to the layer controls + list, but maybe it is about something else. Consider using different language than "menubar" since it is not clear (at least to me) what it refers to.

Critical issue
●●○   Medium design work
▼▼▼   High development work

**Comment by Czaki** [comment]
could You add information about system?

**Comment by liaprins-czi** [comment]
system at time:
MacBook Pro running MacOS Catalina 10.15.5

**Comment by justinelarsen** [comment]
This has been partially fixed by https://github.com/napari/napari/pull/1554. It's unclear how much better we can do without changing the installation instructions for mac users.

**Comment by liu-ziyang** [comment]
there are 2 parts in this issue, the first part does seem to be a side effect of the fixed #1554 where menubar is not really activated and not clickable when napari was opened new, one has to switch out then back for the menubar to function correctly.

The second part regarding menubar visibility, I was also initially confused why menubar visibility is locked at True and toggling doesn't do anything, but it quick strikes me that mac menubar cannot be hidden. In macOS menubar is part of the OS, not the application, so there is no way and no point to hide it. On windows distribution, the menubar is wrapped in the main window and hence can be "hidden" when not being used.
However, this feature is not documented anywhere, and if someone does not know there is a hidden menubar somewhere that can unhide, I bet against his luck ever finding out the shortcut to unhide it. I would rather purpose some auto-hidden design in this case than a manual switch of visibility of such menubar

**Comment by liu-ziyang** [comment]
related to: https://github.com/napari/napari/issues/1252

**Comment by liu-ziyang** [comment]
@liaprins-czi as discussed I think we should spend some time on the design around the menubar, we should finalize on whether it should be hidden or not, and how to hide/unhide it if so. the above issue also have some related context which echos our findings

**Comment by liaprins-czi** [comment]
Okay great, thanks for flagging this @ziyangczi

**Comment by liu-ziyang** [comment]
going to continue future design related conversation in #1252
