### ISSUE TITLE
Pan and zoom bug

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#36]
Pan and zoom was behaving very incorrectly and unexpectedly for me for a while. It would not zoom from the point of cursor, and other inexplicable things on its own. I quit napari and relaunched my Terminal, and it worked well the next time, unsure how to reproduce. Ultimately it crashed my napari instance.
__________________________________________________________
**Recommendation**

Capture on video if anyone notices it again.

Fix so it consistently works.

Critical issue
○○○   No design work
▼▼▼   High development work

**Comment by justinelarsen** [comment]
This may be fixed by https://github.com/napari/napari/pull/1729

**Comment by liu-ziyang** [comment]
This issue is scheduled for our Oct 20th - Nov 2nd Sprint

**Comment by liu-ziyang** [comment]
I checked the existing reports, this does seem to relate to the 1729 fix, closing the ticket now
