### ISSUE TITLE
"Home" button bug

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#37]
Clicking "home" button does not turn my image to the original zoom level, per the tutorial. No action occurs.
Buttons do not work when in conda or opened via jupyter notebook.
__________________________________________________________
**Recommendation**

Clicking button should perform original zoom functionality.

This was an issue with how I installed napari and required closing and troubleshooting. Another recommendation to assess install and flag common errors users might run into, alongside mitigation actions (don’t assume user will file github issue, especially as beginner).

Critical issue
○○○   No design work
▼▼▼   High development work

**Comment by Czaki** [comment]
Which QT version? There is known bug for 5.15 https://github.com/napari/napari/issues/1312. If yoou use 5.15 then try to downgrade to 5.14.2

**Comment by liu-ziyang** [comment]
confirmed this was an issue with qt 5.15.0, we are currently excluding 5.15.0 from our dependency list, so no one should be running into this anymore, home button works normally again with 5.15.1 now
