### ISSUE TITLE
Image view bug

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#39]
If you add a shape layer, then add image via menu option, image layer but does not default view to image. User must click on "reset view" to see image in viewer. Panning/zooming also does not bring image into view.
__________________________________________________________
**Recommendation**

Possible bug related to add image from menu options, review.

Moderate issue
○○○   No design work
▼▼▼   High development work

![Image-view-bug](https://user-images.githubusercontent.com/53277128/95918365-8091ea80-0d60-11eb-803d-38b31afac874.gif)

<img width="989" alt="addimagenoshow" src="https://user-images.githubusercontent.com/53277128/95918418-9d2e2280-0d60-11eb-9f43-40c263028d32.png">
<img width="986" alt="addimagenoshow2" src="https://user-images.githubusercontent.com/53277128/95918422-9ef7e600-0d60-11eb-8e49-730f9459b301.png">

**Comment by justinelarsen** [comment]
This may have been partially fixed in https://github.com/napari/napari/pull/1360 in 0.3.7 release. Testing was done on 0.3.6.

**Comment by liu-ziyang** [comment]
I can confirm this has been fixed, in 0.3.6 version I was seeing the behavior being camera zoomed all the way in on the top left corner, which for the test picture it is all black, zooming out actually shows that we were focusing on the corner.
